INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (1, 'Aguascalientes');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (2, 'Baja California');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (3, 'Baja California Sur');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (4, 'Campeche');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (9, 'CDMX');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (7, 'Chiapas');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (8, 'Chihuahua');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (5, 'Coahuila');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (6, 'Colima');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (10, 'Durango');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (33, 'Extranjero');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (11, 'Guanajuato');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (12, 'Guerrero');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (13, 'Hidalgo');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (14, 'Jalisco');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (15, 'México');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (16, 'Michoacán de Ocampo');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (17, 'Morelos');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (18, 'Nayarit');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (34, 'No Especificado');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (19, 'Nuevo León');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (20, 'Oaxaca de Juárez');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (21, 'Puebla');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (22, 'Querétaro');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (23, 'Quintana Roo');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (24, 'San Luis Potosí');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (25, 'Sinaloa');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (26, 'Sonora');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (27, 'Tabasco');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (28, 'Tamaulipas');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (29, 'Tlaxcala');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (30, 'Veracruz');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (31, 'Yucatán');
INSERT INTO `CatEstados` (`id`, `Estado`) VALUES (32, 'Zacatecas');
